### PR TITLE
Add WebEd CMS

### PR DESCRIPTION
**Pull request by duyphan2502**
WebEd CMS is a new Laravel CMS. It has some awesome features:
- Cache database
- Themes, plugins management
- ACL
- Menu management with drag & drop
- Hook
- Pages management
- Theme options, page settings.
- Blog (posts, categories)
- Custom fields
- Scaleable

**What I'm doing**
- Multilingual
- Ecommerce package.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Doesn't have 100 stars though, so can't be accepted.

**Comment by duyphan2502** [comment]
Ok thank you. I think it will have over 100 stars soon :D

**Comment by duyphan2502** [comment]
Hello @GrahamCampbell , WebEd already had 100 stars.

**Comment by sangnguyenplus** [comment]
Good job :D

**Pull request merged**
