### PR TITLE
Laravel Blade Minify

### PR DESCRIPTION
**Pull request by renatomarinho**

### CODE REVIEW

**Comment by vaidas-lungis** [comment]
Does it give some measurable page performance boost?

**Comment by renatomarinho** [comment]
Yes, http://querobarato.com.br

**Comment by mr0bles** [comment]
**Must haves for Packages, Starter Projects, Codebases etc.**

200 stars on Github.
Support Laravel 5.1 LTS or higher.
Use PSR-4 autoloader.
Packages must be listed on Packagist.
Packages must have also had 10,000 downloads.
Tests!
Utilize Travis-CI or similar CI tools to automatically check coding standards and run tests.

**Comment by GrahamCampbell** [comment]
Not enough stargazers, and https://github.com/HTMLMin/Laravel-HTMLMin already exists.

**Pull request closed without merging**
