### PR TITLE
Add Laravel Tactician

### PR DESCRIPTION
**Pull request by joselfonseca**
https://github.com/joselfonseca/laravel-tactician

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
How does this compare to https://github.com/madewithlove/tactician-laravel for example?

**Comment by GrahamCampbell** [comment]
I think maybe less than 100 stars indicates not very many users?

**Comment by joselfonseca** [comment]
Hi there. They are very similar however the way each one works is different. Laravel Tactician's configuration and its bus is based on tactician but very similar to what Jeffrey Way did with commander https://github.com/laracasts/Commander where you can map the input to the command and i am not trying to replace Laravel Jobs as it can be use with them.

I understand not many stars means not much usage, i haven't really broadcast it since i've been using it in our products. So if that is a reason for it to not be in i am cool with that.

Thanks for reviewing.

**Comment by chiraggude** [comment]
As Graham said, not enough stars - https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md#must-haves-for-packages

**Pull request closed without merging**
