### PR TITLE
Add Secure Headers

### PR DESCRIPTION
**Pull request by BePsvPT**
[Secure Headers](https://github.com/BePsvPT/secure-headers) is a package that allow you to add security related headers to HTTP response.

The package is inspired by [twitter/secureheaders](https://github.com/twitter/secureheaders).

### CODE REVIEW

**Comment by HDVinnie** [comment]
I use this package.....well worth adding to the list

**Comment by mr0bles** [comment]
**Must haves for Packages, Starter Projects, Codebases etc.**

200 stars on Github.
Support Laravel 5.1 LTS or higher.
Use PSR-4 autoloader.
Packages must be listed on Packagist.
Packages must have also had 10,000 downloads.
Tests!
Utilize Travis-CI or similar CI tools to automatically check coding standards and run tests.

**Comment by GrahamCampbell** [comment]
👎 for two reasons.

1. Not enough stargazers.
2. I don't like the package - I think it's better to add these headers at the nginx level.

**Comment by BePsvPT** [comment]
@GrahamCampbell 

When using vps, I agree with you that add these headers to config file is more suitable. However, you may not always have the permission to modify config file, like using shared hosting service.  In this situation, I think this package can help a lot.

Besides, the risk of modifying web service config is higher than using this package. When there is something wrong, it will result in web service down instead of specific header not works. If your website is high traffic, I think even if it is down for few seconds is not acceptable.

At last, security is getting more and more important nowadays. In Awesome Laravel, I do not see any other similar package in this repo. I know this package does not have 200 stars on GitHub, but it has 18k total downloads. I think it is enough to support me to submit pull request to this repo.

Thanks you give me the feedback and every one who use this package.

**Pull request closed without merging**
