### PR TITLE
removed laravel spark

### PR DESCRIPTION
**Pull request by actuallymab**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Spark still exists. It's coming back soon.

**Comment by peter-mw** [comment]
@GrahamCampbell probably won't be public on GitHub?

**Comment by actuallymab** [comment]
@GrahamCampbell am I missing sth? It will be paid, not planned as an open source project again.

**Comment by dikiaap** [comment]
@GrahamCampbell come back with Freemium?

**Comment by GrahamCampbell** [comment]
paid only

**Pull request merged**
