### PR TITLE
Add Larasupport Package

### PR DESCRIPTION
**Pull request by irazasyed**
This package adds support to Lumen, So any Laravel Package could be used in Lumen without having to modify packages to support Lumen.

### CODE REVIEW

**Comment by irazasyed** [comment]
Care to explain why this was not merged? @chiraggude

**Comment by chiraggude** [comment]
Main reason for not accepting this PR was that the package is not "popular" enough to belong on the list - I know that sounds shallow. On second thoughts, give me a couple of days to test the package myself.

**Comment by irazasyed** [comment]
What's the criteria of a "popular" package? It has 2k downloads and is a helpful package. It just doesn't have more stars if that's what you're looking for?

Anyway, Sure! Check out the package.

**Comment by chiraggude** [comment]
See #118 for more info

**Pull request closed without merging**
