### PR TITLE
Add Laravel MultiMix

### PR DESCRIPTION
**Pull request by pi0**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Not enough stars. Minimum 100 required, sorry.

**Comment by GrahamCampbell** [comment]
https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md#must-haves-for-packages-starter-projects-codebases-etc

**Comment by pi0** [comment]
@GrahamCampbell Oh :)) Actually we just open sourced workaround today and wanted to spread to world through github awesome channel. It's okay if you have to close this one ;)

**Comment by GrahamCampbell** [comment]
I'm not a maintainer of this repo. :)

**Comment by chiraggude** [comment]
Agree with Graham. Not enough stars.

You should share your package on Reddit and Slack to spread the word! :)

https://www.reddit.com/r/laravel/
https://larachat.co/

**Pull request closed without merging**
