### PR TITLE
Add travis tests

### LINKED ISSUE #135: Validate pull requests with Travis
Hello, I wrote a tool that can validate README links (valid URLs, not duplicate). It can be run when someone submits a pull request. 

 It is currently being used by 
- https://github.com/vsouza/awesome-ios 
- https://github.com/matteocrippa/awesome-swift 
- https://github.com/dkhamsing/open-source-ios-apps 

Examples 
- https://travis-ci.org/matteocrippa/awesome-swift/builds/96526196 ok ✅
- https://travis-ci.org/matteocrippa/awesome-swift/builds/96722421 link redirected / rename 🔴
- https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/96763135 bad link / project deleted 🔴
- https://travis-ci.org/dkhamsing/open-source-ios-apps/builds/95754715 dupe 🔴

If you are interested, connect this repo to https://travis-ci.org/ and add a [`.travis.yml`](https://github.com/dkhamsing/open-source-ios-apps/blob/master/.travis.yml) file to the project. 

See https://github.com/dkhamsing/awesome_bot for options, more information 
Feel free to leave a comment :smile:

### PR DESCRIPTION
**Pull request by vinkla**
This will test all new link additions before we merge them in. Now we only need to enable Travis tests on this repository.

This closes #135

### CODE REVIEW

**Comment by vinkla** [comment]
@chiraggude any update on this? I'll fix the tests as soon as you've enabled Travis.

**Comment by vinkla** [comment]
@chiraggude any update on this?

**Comment by vinkla** [comment]
@chiraggude any update on this? If you add me to the repository I could help you set this up. Just let me know. I would be happy to help out.

**Comment by vinkla** [comment]
@chiraggude any update on this? If you add me to the repository I could help you set this up. Just let me know. I would be happy to help out.

**Comment by chiraggude** [comment]
Will do it this weekend. Promise! :)

**Comment by vinkla** [comment]
Good 👍 I can fix the broken links earliest next Tuesday.

**Comment by vinkla** [comment]
Did you get a chance to look at it?

**Comment by vinkla** [comment]
Did you get a chance to look at it?

**Pull request merged**
