### PR TITLE
Update README.md - Remove StyleCI

### PR DESCRIPTION
**Pull request by christianpv**
Removing StyleCI as its not available anymore.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
No, it just has a new home. https://styleci.io/

**Comment by a-komarev** [comment]
@GrahamCampbell after moving to new home there are connection issues then. It's not available from Russia anymore.

**Comment by GrahamCampbell** [comment]
> It's not available from Russia anymore.

What! Really! That shouldn't be happening.

**Comment by GrahamCampbell** [comment]
I see no blocks from Russia on our firewalls. Is your service provider blocking CloudFlare?

**Comment by GrahamCampbell** [comment]
> there are connection issues then

What sort of issues? Is it related to DNS, or SSL?

**Comment by GrahamCampbell** [comment]
We are seeing plenty of other users from Russia successfully accessing StyleCI without a proxy?

**Comment by a-komarev** [comment]
@GrahamCampbell And I'm currently using one of the biggest service providers in Russia.

> PING styleci.io (108.162.201.30) 56(84) bytes of data.
> 1454 packets transmitted, 0 received, 100% packet loss, time 1460385ms

**Comment by GrahamCampbell** [comment]
That IP address belongs to CloudFlare, not us, so it looks like your service provider is blocking loads of websites.

**Comment by GrahamCampbell** [comment]
Including laravel.com, actually!

**Comment by GrahamCampbell** [comment]
Anyway, there's no way this should be removed considering Laravel itself uses StyleCI everyday. It's setup on laravel/framework, and other laravel repos as a CI service, along with travis.

**Comment by GrahamCampbell** [comment]
> Including laravel.com, actually!

Unless Taylor has taken it off CloudFlare again. I know he had it enabled when there was a DDOS a few days ago

**Comment by a-komarev** [comment]
@GrahamCampbell Nope. I'm visiting a lot of websites who using CloudFlare and there are no problems.

> PING laravel.com (141.101.112.207) 56(84) bytes of data.
> 2 packets transmitted, 2 received, 0% packet loss, time 999ms

**Comment by GrahamCampbell** [comment]
I guess it's just those CloudFlare websites assigned the same IP as us. I'll see if I can find some.

**Comment by GrahamCampbell** [comment]
I'm going to report this issue to CloudFlare. Can I have the name of your service provider please.

**Comment by a-komarev** [comment]
And usually when CloudFlare is blocking access it's displaying their branded page which tell user about blocks. But there are not response at all from their server.

**Comment by a-komarev** [comment]
Telco: Beeline. Company legal name: Vympelkom

**Comment by GrahamCampbell** [comment]
CloudFlare are not blocking you, as I said. I'd know if they were because they'd show me on the logs. You're unable to even reach the IP address. I'm going to ask them, and see what they say. I'll keep you posted.

**Comment by GrahamCampbell** [comment]
Out of interest, is https://alt-three.com/, and https://cachethq.io/ also broken?

**Comment by a-komarev** [comment]
@GrahamCampbell I think there is a possibility of block on side of Russian service provider, because they are trying to block illegal sites and one of them could be on same IP in CloudFlare with you.

> Out of interest, is https://alt-three.com/, and https://cachethq.io/ also broken?

Both working.

**Comment by GrahamCampbell** [comment]
Thanks. CloudFlare support say, can you please run a traceroute.

https://support.cloudflare.com/hc/en-us/articles/200169336-How-do-I-run-a-traceroute-

**Comment by GrahamCampbell** [comment]
@a-komarev Also, is there anything I can do to say thank you for helping us with this issue. Would you like some of our stickers, or a discount code?

**Comment by a-komarev** [comment]
@GrahamCampbell Nope. Just trying to support OSS as I can :+1: 

Traceroute tells me that I'm not going out from telco side. So, this IP is blocked on my service provider :'(

**Comment by jbrooksuk** [comment]
👎 for the PR. Like Graham said, we just rock a new home.

**Comment by GrahamCampbell** [comment]
Well, CloudFlare's attitude is:

> Without the traceroute it's impossible to say I'm afraid. It could simply be an ISP level issue, or it could indeed be a block- we know Russian ISPs heavily censor certain types of content.

> One way of making sure that the IP's you have are shared with no one but yourself is to upload a Custom SSL certificate (Only available on the CloudFlare business plan and above)

We can't afford to start paying that amount of money I'm afraid since we only make enough money to support our running costs to help out open source projects, and students.

---

I can only suggest at this point, that you take this up with your ISP, and complain they are blocking a website for no good reason.

---

CloudFlare have said:

> We can't move IPs in this manner I'm afraid- I can ask for our Trust & Safety team to investigate and see if there's a way to remove the block, but I can't guarantee this.

That response sounds a bit like they're not actually going to do anything though.

---

Sorry I can't provide better news.

**Comment by a-komarev** [comment]
@GrahamCampbell I requested feedback from ISP, tech team would contact with me later, they said. Not sure they would solve this issue. Anyway, confirming that this PR could be closed, service is alive.

**Comment by GrahamCampbell** [comment]
@chiraggude Can you please close this PR. It's outvoted.

**Comment by GrahamCampbell** [comment]
Replaced by https://github.com/chiraggude/awesome-laravel/pull/159.

**Comment by christianpv** [comment]
@GrahamCampbell First of all, I use StyleCI, and recommend it myself, but you are going over a committer because it doesn't do you any good. This PR is not outvoted because the owners don't count as it benefits you. If you wanted to discuss why I remove it, we could do it here, you shouldn't have gone out of your way to create a new PR for that. I believe it belongs to the Hosted Development Tools as said by @chiraggude in #159 . StyleCI is not essential to using Laravel. If you are saying that because Laravel is using it, what about TravisCI? We don't mention it anywhere. Those are services that you could use with Laravel but are not required.

**Comment by GrahamCampbell** [comment]
Well, nothing is essential to using Laravel really.

**Pull request closed without merging**
