### PR TITLE
add Lavatar Package

### PR DESCRIPTION
**Pull request by vinicius73**
https://github.com/vinicius73/lavatar

### CODE REVIEW

**Comment by chiraggude** [comment]
I have been inundated with a large number of pull requests after Taylor Otwell retweeted a link to this repo. Starting now, I will be adding links to the "Popular Packages" section, only if the package has received more than 200 stars on Github or 1000+ downloads via Packagist. Because of this pre-requisite, a lot of helpful packages will fall through the cracks – but I think this fair to everyone involved. Apologies for the inconvenience.

**Comment by vinkla** [comment]
@chiraggude That sounds good :+1: Though, it is possible to spoof the downloads count on Packagist.

**Comment by vinkla** [comment]
@chiraggude Isn't 100 stars enough?

**Comment by chiraggude** [comment]
@vinkla I need to keep the bar a little high - I don't want this repo to be an alternative to Packagist or Packagist which are primarily mean't to discover packages

**Comment by chiraggude** [comment]
@vinkla I think, I will keep the limit to 200 github stars or more....as you rightly said, number of downloads can be spoofed.

**Comment by vinkla** [comment]
@chiraggude That is true. Though, 200 is very hard to get. Other points that I think would be better is;

- If the package is tested
- If the package has integrated a CI like Travis
- If the package runs code coverage
- If the package has well written documentation
- If the package has a license file
- If the package keep an active changelog
- If the package is updated for newer versions of Laravel

Etc.

**Comment by vinkla** [comment]
Moved this discussion to #118.

**Comment by vinicius73** [comment]
No problem. Thanks for the feedback

**Pull request closed without merging**
