### PR TITLE
Add Gravatar Package

### PR DESCRIPTION
**Pull request by arcanedev-maroc**
[Gravatar](https://github.com/ARCANEDEV/Gravatar) - Gravatar Helper & Generator (Laravel 5 supported).

:+1:

### CODE REVIEW

**Comment by chiraggude** [comment]
I have been inundated with a large number of pull requests after Taylor Otwell retweeted a link to this repo. Starting now, I will be adding links to the "Popular Packages" section, only if the package has received more than 200 stars on Github or 1000+ downloads via Packagist. Because of this pre-requisite, a lot of helpful packages will fall through the cracks – but I think this fair to everyone involved. Apologies for the inconvenience.

**Comment by chiraggude** [comment]
See #118 for more info

**Comment by arcanedev-maroc** [comment]
Ok, no problemo.

**Comment by arcanedev-maroc** [comment]
@chiraggude After reading the [CONTRIBUTING.md](https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md), the rule about github stars was removed.

So, can you please open this pull request ?

> Note : The only thing that package is missing, is the changelog (Even laravel has not, check https://github.com/laravel/framework or https://github.com/laravel/laravel)

**Comment by chiraggude** [comment]
Hey buddy, I have just finished editing the contribution guide. Give me some more time to clean things up, link things properly etc. :)

**Comment by arcanedev-maroc** [comment]
Ok, let me know if everything is done :+1:

**Comment by chiraggude** [comment]
Done!

**Comment by arcanedev-maroc** [comment]
Ok, tnx.

Now i'm just gonna wait for 100 stars :disappointed:.

**Comment by chiraggude** [comment]
Sorry, I have to be fair with everyone. You'll get there sooner than later :thumbsup:

Also, send me a PR when https://github.com/ARCANEDEV/LogViewer hits 100 stars. Looks so good!

**Comment by arcanedev-maroc** [comment]
Of course :+1: .

> BTW, you've already added one of my package (Utilities => noCaptcha) :wink: .

**Comment by chiraggude** [comment]
Haha!

**Pull request closed without merging**
