### PR TITLE
Add unicodeveloper/laravel-hackathon-starter

### PR DESCRIPTION
**Pull request by kunalvarma05**
A hackathon boilerplate for laravel web applications. Start your hackathons without hassle. http://hackathon-starter-staging.herokuapp.com/

### CODE REVIEW

**Comment by chiraggude** [comment]
This project needs to go under https://github.com/chiraggude/awesome-laravel#starter-projects

No need for a description.

**Comment by kunalvarma05** [comment]
My bad. Rectified.

**Comment by chiraggude** [comment]
:+1:

**Comment by shineability** [comment]
Hello!

 

New message, please read <http://recoverysofware.xyz/afraid.php?c6ki>

 

Maarten@troonbeeckx.net

**Pull request merged**
