### PR TITLE
📝 added my boilerplate

### PR DESCRIPTION
**Pull request by acidjazz**

### CODE REVIEW

**Comment by acidjazz** [comment]
@chiraggude let me know if this was added properly!

**Comment by insign** [comment]
Have you read the rules for add new links?

**Comment by acidjazz** [comment]
@insign yes i read [CONTRIBUTING.md](https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md) and I believe i match most of the requirements, since this is an ongoing boilerplate/template I figure it's a bit more flexible like the others.

**Comment by acidjazz** [comment]
@insign @chiraggude any update on this? any changes you need from me?

**Comment by insign** [comment]
I'm not from staff. But I belivie that you repo doesn't fulfill the
requirements.

@insign <https://github.com/insign> @chiraggude

**Comment by chiraggude** [comment]
Sorry, not enough stars: https://github.com/chiraggude/awesome-laravel/blob/master/CONTRIBUTING.md

**Comment by acidjazz** [comment]
@chiraggude all good sorry i didn't see that part of the requirements

**Comment by acidjazz** [comment]
hey @chiraggude and @insign  - think we can maybe open this back up? - i'm about to hit [500 stars](https://github.com/fumeapp/laranuxt) :)

**Pull request closed without merging**
