### PR TITLE
Add Deployer

### PR DESCRIPTION
**Pull request by vinkla**
Add Deployer by @REBELinBLUE

### CODE REVIEW

**Comment by REBELinBLUE** [comment]
Oooh, thanks :D

**Comment by vinkla** [comment]
:+1:

**Comment by chiraggude** [comment]
Suggestion: Try to get featured on laravel-news.com - get in touch with  @ericlbarnes on twitter. Although you have some screenshots, it's easy to miss the link to view them - you could add some to your project's landing page.

**Comment by vinkla** [comment]
@chiraggude That is a good idea! Also, you could try submitting it in their suggestion box https://laravel-news.com/submit/

**Comment by REBELinBLUE** [comment]
Thanks, I'll take a look.

**Pull request merged**
